apiVersion: apps/v1
kind: Deployment
metadata:
  name: apex-analyticsapp
  namespace: apex-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyticsapp
  template:
    metadata:
      labels:
        app: analyticsapp
    spec:
      containers:
      - name: analyticsapp
        image: registry.marcel.im/atosanalyticsapp
        ports:
        - containerPort: 3838
---
apiVersion: v1
kind: Service
metadata:
  name: apex-entrypoint
  namespace: apex-demo
spec:
  type: ClusterIP
  selector:
    app: analyticsapp
  ports:
  - port: 80
---
# ingress controller
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: apexdemo-ingress
  namespace: apex-demo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: demo.apex.atoscloud.org
    http:
      paths:
      - backend:
          serviceName: apex-entrypoint
          servicePort: 80
        path: /.*


