# oath
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
  namespace: apex-demo
spec:
  type: ClusterIP
  ports:
    - port: 4180
      targetPort: 4180
      protocol: TCP
      name: web
  selector:
    app: "oauth-proxy"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
  namespace: apex-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth-proxy"
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      containers:
      - name: oauth-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy
        env:
          # OIDC Config
          - name: "OAUTH2_PROXY_PROVIDER"
            value: "azure"
          - name: "OAUTH2_PROXY_AZURE_TENANT"
            value: "x"
          - name: "OAUTH2_PROXY_CLIENT_ID"
            value: "x"
          - name: "OAUTH2_PROXY_CLIENT_SECRET"
            value: "x"

          # Cookie Config
          #- name: "OAUTH2_PROXY_COOKIE_SECURE"
          #  value: "false"
          - name: "OAUTH2_PROXY_COOKIE_SECRET"
            value: "0123456789012345"
          - name: "OAUTH2_PROXY_COOKIE_SAMESITE"
            value: "lax"
          - name: "OAUTH2_PROXY_COOKIE_DOMAINS"
            value: ".apex.atoscloud.org"
          - name: "OAUTH2_PROXY_SESSION_STORE_TYPE"
            value: "redis"
          - name: "OAUTH2_PROXY_REDIS_CONNECTION_URL"
            value: "redis://apexdemo.redis.cache.windows.net:6379"
          - name: "OAUTH2_PROXY_REDIS_PASSWORD"
            value: "x"


          #Proxy Config
          - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
            value: "*"
          - name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
            value: ".apex.atoscloud.org"
          - name: "OAUTH2_PROXY_HTTP_ADDRESS"
            value: "0.0.0.0:4180"
          - name: "OAUTH2_PROXY_SET_XAUTHREQUEST"
            value: "true"
          - name: "OAUTH2_PROXY_UPSTREAMS"
            value: "file:///dev/null"
---
# ingress
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
  namespace: apex-demo
spec:
  rules:
    - host: auth.apex.atoscloud.org
      http:
        paths:
          - backend:
              serviceName: oauth-proxy
              servicePort: 4180
